variables:
  NPM_AUDIT_LEVEL: "high"
  NPM_AUDIT_FLAGS: "--production"

include:
  - project: 'build/standard-pipelines'
    file: '/default.gitlab-ci.yml'

# Override standard pipeline to never deploy. Remove this if you are using the scaffolding to deploy a new service
deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "never"'
